# See ./amulet_readme.md for setup, and run with:
# scripts/amlt_runner.sh philly_configs/train_blas_itp_ray.yaml ....

target:
  service: amlk8s
  name: itplabrr1cl1
  vc: resrchvc

environment:
  image: knossos.azurecr.io/rlo_linux_base:$DOCKER_TAG
  registry: knossos.azurecr.io
  #username: knossos # If using repo access key (az acr credential show) after PIM elevation
  # Username below is appropriate for use with a temporary token (az acr login --expose-token)
  username: 00000000-0000-0000-0000-000000000000

code:
  local_dir: src

jobs:
 - name: "test_blas_ray_job"
   sku: G4
   command:
   - python ray_main.py blas
     --output_dir $$PT_OUTPUT_DIR
     --force_gpu
     --num_gpus=4
     --workers_per_gpu=2 --gpu_memory_fraction=0.5
     --num_repetitions=8
     --run_id blas2 --save_all_models
     # The last only required to resume following pre-emption.
     # Note --workers_per_gpu=2 --gpu_memory_fraction=0.5 is optional, should improve speed for small models, but may fail with large models.
   submit_args:
    max_attempts: 1
