name: Python checks (format, lint)

on:

# when we get errors down, can add as PR check
#   pull_request:
#     branches: [ master ]
    
  push:
    branches: [cogravil/blackandflake]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black flake8 
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # start with Python syntax errors or undefined names, remove exit-zero once handled
        flake8 . --count --exit-zero --select=E9,F63,F7,F82 --show-source --statistics --exclude pybind11,mlir
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check format with Black
      # current releleased version of Black doesn't have extend-exclude, so add pybind11 and mlir to default extend until released 
      run: |
        black . --check
      
